name: Salus Security Scan

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Salus Scan
        id: salus_scan
        uses: federacy/scan-action@0.1.4
        with:
          active_scanners: "\n  - PatternSearch\n  - Semgrep\n  - Trufflehog"
